CREATE TABLE characters (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    personality      VARCHAR(500) NULL,
    design_keyword   VARCHAR(120) NULL,
    sprite_sheet_url TEXT NULL,
    sprite_meta      JSONB NULL,
    image_status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_characters_design_keyword
        CHECK (design_keyword IS NULL OR design_keyword ~ '[^[:space:]]'),
    CONSTRAINT ck_characters_personality
        CHECK (personality IS NULL OR personality ~ '[^[:space:]]'),
    CONSTRAINT ck_characters_image_status
        CHECK (image_status IN ('PENDING', 'READY', 'FALLBACK', 'FAILED')),
    CONSTRAINT ck_characters_ready_or_fallback_requires_sprite
        CHECK (
            image_status NOT IN ('READY', 'FALLBACK')
            OR (sprite_sheet_url IS NOT NULL AND sprite_sheet_url ~ '[^[:space:]]')
        )
);

CREATE INDEX idx_characters_created_at
    ON characters (created_at DESC);

INSERT INTO characters (
    id,
    personality,
    design_keyword,
    sprite_sheet_url,
    sprite_meta,
    image_status
)
VALUES
    (
        1,
        NULL,
        NULL,
        '/character-assets/default_image1.png',
        '{"columns":3,"rows":1,"frameMap":{"joy":[0,0],"sad":[0,1],"angry":[0,2]},"transparent":true}'::jsonb,
        'READY'
    ),
    (
        2,
        NULL,
        NULL,
        '/character-assets/default_image2.png',
        '{"columns":3,"rows":1,"frameMap":{"joy":[0,0],"sad":[0,1],"angry":[0,2]},"transparent":true}'::jsonb,
        'READY'
    ),
    (
        3,
        NULL,
        NULL,
        '/character-assets/default_image3.png',
        '{"columns":3,"rows":1,"frameMap":{"joy":[0,0],"sad":[0,1],"angry":[0,2]},"transparent":true}'::jsonb,
        'READY'
    );

SELECT setval(pg_get_serial_sequence('characters', 'id'), (SELECT max(id) FROM characters));
