CREATE TABLE characters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    name            VARCHAR(40) NOT NULL,
    design_keyword  VARCHAR(120) NOT NULL,
    personality     VARCHAR(500) NOT NULL,
    stat_db         INTEGER NOT NULL DEFAULT 0,
    stat_algorithm  INTEGER NOT NULL DEFAULT 0,
    stat_cs         INTEGER NOT NULL DEFAULT 0,
    stat_network    INTEGER NOT NULL DEFAULT 0,
    stat_framework  INTEGER NOT NULL DEFAULT 0,
    battle_power    INTEGER NOT NULL DEFAULT 0,
    emotion         VARCHAR(20) NOT NULL DEFAULT 'JOY',
    status_message  VARCHAR(160) NOT NULL,
    is_evolved      BOOLEAN NOT NULL DEFAULT false,
    image_status    VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    sprite_sheet_url TEXT NULL,
    sprite_meta     JSONB NULL,
    is_active       BOOLEAN NOT NULL DEFAULT false,
    version         BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_characters_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ck_characters_name
        CHECK (name ~ '[^[:space:]]'),
    CONSTRAINT ck_characters_design_keyword
        CHECK (design_keyword ~ '[^[:space:]]'),
    CONSTRAINT ck_characters_personality
        CHECK (personality ~ '[^[:space:]]'),
    CONSTRAINT ck_characters_status_message
        CHECK (status_message ~ '[^[:space:]]'),
    CONSTRAINT ck_characters_stats_non_negative
        CHECK (
            stat_db >= 0
            AND stat_algorithm >= 0
            AND stat_cs >= 0
            AND stat_network >= 0
            AND stat_framework >= 0
        ),
    CONSTRAINT ck_characters_battle_power
        CHECK (battle_power = stat_db + stat_algorithm + stat_cs + stat_network + stat_framework),
    CONSTRAINT ck_characters_emotion
        CHECK (emotion IN ('JOY', 'SAD', 'ANGRY')),
    CONSTRAINT ck_characters_image_status
        CHECK (image_status IN ('PENDING', 'READY', 'FALLBACK', 'FAILED')),
    CONSTRAINT ck_characters_ready_or_fallback_requires_sprite
        CHECK (
            image_status NOT IN ('READY', 'FALLBACK')
            OR (sprite_sheet_url IS NOT NULL AND sprite_sheet_url ~ '[^[:space:]]')
        )
);

CREATE UNIQUE INDEX uq_one_active_character_per_user
    ON characters (user_id)
    WHERE is_active = true;

CREATE INDEX idx_characters_user_created_at
    ON characters (user_id, created_at DESC);

CREATE INDEX idx_characters_user_active
    ON characters (user_id, is_active);
