CREATE TABLE user_character (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    character_id    BIGINT NOT NULL,
    name            VARCHAR(40) NOT NULL,
    stat_db         INTEGER NOT NULL DEFAULT 0,
    stat_algorithm  INTEGER NOT NULL DEFAULT 0,
    stat_cs         INTEGER NOT NULL DEFAULT 0,
    stat_network    INTEGER NOT NULL DEFAULT 0,
    stat_framework  INTEGER NOT NULL DEFAULT 0,
    battle_power    INTEGER NOT NULL DEFAULT 0,
    emotion         VARCHAR(20) NOT NULL DEFAULT 'JOY',
    status_message  VARCHAR(160) NOT NULL DEFAULT 'Ready to learn',
    is_evolved      BOOLEAN NOT NULL DEFAULT false,
    is_active       BOOLEAN NOT NULL DEFAULT false,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ NULL,
    CONSTRAINT fk_user_character_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_user_character_character
        FOREIGN KEY (character_id) REFERENCES characters(id),
    CONSTRAINT ck_user_character_name
        CHECK (name ~ '[^[:space:]]'),
    CONSTRAINT ck_user_character_status_message
        CHECK (status_message ~ '[^[:space:]]'),
    CONSTRAINT ck_user_character_stats_non_negative
        CHECK (
            stat_db >= 0
            AND stat_algorithm >= 0
            AND stat_cs >= 0
            AND stat_network >= 0
            AND stat_framework >= 0
        ),
    CONSTRAINT ck_user_character_battle_power
        CHECK (battle_power = stat_db + stat_algorithm + stat_cs + stat_network + stat_framework),
    CONSTRAINT ck_user_character_emotion
        CHECK (emotion IN ('JOY', 'SAD', 'ANGRY'))
);

CREATE UNIQUE INDEX uq_one_active_character_per_user
    ON user_character (user_id)
    WHERE is_active = true AND deleted_at IS NULL;

CREATE INDEX idx_user_character_user_created_at
    ON user_character (user_id, created_at DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_user_character_user_active
    ON user_character (user_id, is_active)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_user_character_character
    ON user_character (character_id);
