CREATE TABLE report_request_outbox (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id                  VARCHAR(120) NOT NULL,
    user_id                     BIGINT NOT NULL,
    character_id                BIGINT NOT NULL,
    target_date                 DATE NOT NULL,
    report_title                VARCHAR(200) NOT NULL,
    report_content              TEXT NOT NULL,
    weekly_study_streak         CHAR(7) NOT NULL,
    focus                       VARCHAR(300) NOT NULL,
    character_name              VARCHAR(40) NOT NULL,
    character_personality       VARCHAR(500) NOT NULL,
    character_emotion           VARCHAR(20) NOT NULL,
    character_stat_db           INTEGER NOT NULL DEFAULT 0,
    character_stat_algorithm    INTEGER NOT NULL DEFAULT 0,
    character_stat_cs           INTEGER NOT NULL DEFAULT 0,
    character_stat_network      INTEGER NOT NULL DEFAULT 0,
    character_stat_framework    INTEGER NOT NULL DEFAULT 0,
    score_delta_hint_db         INTEGER NOT NULL DEFAULT 0,
    score_delta_hint_algorithm  INTEGER NOT NULL DEFAULT 0,
    score_delta_hint_cs         INTEGER NOT NULL DEFAULT 0,
    score_delta_hint_network    INTEGER NOT NULL DEFAULT 0,
    score_delta_hint_framework  INTEGER NOT NULL DEFAULT 0,
    status                      VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count               INTEGER NOT NULL DEFAULT 0,
    available_at                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at                     TIMESTAMPTZ NULL,
    last_error                  VARCHAR(500) NULL,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_report_request_outbox_request_id
        UNIQUE (request_id),
    CONSTRAINT uq_report_request_outbox_user_character_date
        UNIQUE (user_id, character_id, target_date),
    CONSTRAINT fk_report_request_outbox_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_request_outbox_character
        FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT ck_report_request_outbox_request_id
        CHECK (request_id ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_title
        CHECK (report_title ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_content
        CHECK (report_content ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_weekly_study_streak
        CHECK (weekly_study_streak ~ '^[01]{7}$'),
    CONSTRAINT ck_report_request_outbox_focus
        CHECK (focus ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_character_snapshot
        CHECK (
            character_name ~ '[^[:space:]]'
            AND character_personality ~ '[^[:space:]]'
            AND character_emotion IN ('JOY', 'SAD', 'ANGRY')
        ),
    CONSTRAINT ck_report_request_outbox_character_stats
        CHECK (
            character_stat_db >= 0
            AND character_stat_algorithm >= 0
            AND character_stat_cs >= 0
            AND character_stat_network >= 0
            AND character_stat_framework >= 0
        ),
    CONSTRAINT ck_report_request_outbox_score_hints
        CHECK (
            score_delta_hint_db BETWEEN 0 AND 10
            AND score_delta_hint_algorithm BETWEEN 0 AND 10
            AND score_delta_hint_cs BETWEEN 0 AND 10
            AND score_delta_hint_network BETWEEN 0 AND 10
            AND score_delta_hint_framework BETWEEN 0 AND 10
        ),
    CONSTRAINT ck_report_request_outbox_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT ck_report_request_outbox_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_report_request_outbox_sent_at_status
        CHECK (
            (status = 'SENT' AND sent_at IS NOT NULL)
            OR (status <> 'SENT' AND sent_at IS NULL)
        )
);

CREATE INDEX idx_report_request_outbox_pending_available
    ON report_request_outbox (available_at, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_report_request_outbox_user_date
    ON report_request_outbox (user_id, target_date DESC);
