CREATE TABLE report_request_outbox (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id          VARCHAR(120) NOT NULL,
    user_id             BIGINT NOT NULL,
    user_character_id   BIGINT NOT NULL,
    target_date         DATE NOT NULL,
    report_title        VARCHAR(200) NOT NULL,
    report_content      TEXT NOT NULL,
    weekly_study_streak CHAR(7) NOT NULL,
    score_delta_hint    JSONB NOT NULL DEFAULT '{}'::jsonb,
    focus               VARCHAR(300) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    attempt_count       INTEGER NOT NULL DEFAULT 0,
    available_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at             TIMESTAMPTZ NULL,
    last_error          TEXT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_report_request_outbox_request_id
        UNIQUE (request_id),
    CONSTRAINT uq_report_request_outbox_user_character_date
        UNIQUE (user_id, user_character_id, target_date),
    CONSTRAINT fk_report_request_outbox_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_report_request_outbox_user_character
        FOREIGN KEY (user_character_id) REFERENCES user_character(id) ON DELETE CASCADE,
    CONSTRAINT ck_report_request_outbox_request_id
        CHECK (request_id ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_title
        CHECK (report_title ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_content
        CHECK (report_content ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_weekly_study_streak
        CHECK (weekly_study_streak ~ '^[01]{7}$'),
    CONSTRAINT ck_report_request_outbox_focus
        CHECK (focus ~ '[^[:space:]]'),
    CONSTRAINT ck_report_request_outbox_score_delta_hint
        CHECK (jsonb_typeof(score_delta_hint) = 'object'),
    CONSTRAINT ck_report_request_outbox_status
        CHECK (status IN ('PENDING', 'SENT', 'FAILED')),
    CONSTRAINT ck_report_request_outbox_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_report_request_outbox_sent_at_status
        CHECK (
            (status = 'SENT' AND sent_at IS NOT NULL)
            OR (status <> 'SENT' AND sent_at IS NULL)
        )
);

CREATE INDEX idx_report_request_outbox_pending_available
    ON report_request_outbox (available_at, id)
    WHERE status = 'PENDING';

CREATE INDEX idx_report_request_outbox_user_date
    ON report_request_outbox (user_id, target_date DESC);
