CREATE TABLE codex_character_reviews (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    character_id BIGINT NOT NULL,
    stars        INTEGER NOT NULL,
    text         VARCHAR(1000) NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_codex_character_reviews_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_codex_character_reviews_character
        FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE,
    CONSTRAINT ck_codex_character_reviews_stars
        CHECK (stars BETWEEN 1 AND 5),
    CONSTRAINT ck_codex_character_reviews_text
        CHECK (text ~ '[^[:space:]]')
);

CREATE UNIQUE INDEX uq_codex_character_review_user_character
    ON codex_character_reviews (user_id, character_id);

CREATE INDEX idx_codex_character_reviews_character_created_at
    ON codex_character_reviews (character_id, created_at DESC, id DESC);
